const data = [
  {
    anzsco: "222213",
    occupation: "Stockbroking Dealer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "222299",
    occupation: "Financial Dealers nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "222311",
    occupation: "Financial Investment Adviser",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "222312",
    occupation: "Financial Investment Manager",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "223111",
    occupation: "Human Resource Adviser",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "223112",
    occupation: "Recruitment Consultant",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "223113",
    occupation: "Workplace Relations Adviser",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "223211",
    occupation: "ICT Trainer",
    list: "STSOL",
    skillLevel: "1",
  },
  { anzsco: "224111", occupation: "Actuary", list: "MLTSSL", skillLevel: "1" },
  {
    anzsco: "224113",
    occupation: "Statistician",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "224212",
    occupation: "Gallery or Museum Curator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "224213",
    occupation: "Health Information Manager",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "224214",
    occupation: "Records Manager",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "224311",
    occupation: "Economist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "224412",
    occupation: "Policy Analyst",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "224511",
    occupation: "Land Economist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "224512", occupation: "Valuer", list: "MLTSSL", skillLevel: "1" },
  { anzsco: "224611", occupation: "Librarian", list: "STSOL", skillLevel: "1" },
  {
    anzsco: "224711",
    occupation: "Management Consultant",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "224712",
    occupation: "Organisation and Methods Analyst",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "224912",
    occupation: "Liaison Officer",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "224914",
    occupation: "Patents Examiner",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "224999",
    occupation: "Information and Organisation Professionals nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225111",
    occupation: "Advertising Specialist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225112",
    occupation: "Market Research Analyst",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "225113",
    occupation: "Marketing Specialist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225211",
    occupation: "ICT Account Manager",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225212",
    occupation: "ICT Business Development Manager",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225213",
    occupation: "ICT Sales Representative",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "224112",
    occupation: "Mathematician",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225311",
    occupation: "Public Relations Professional",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "225499",
    occupation: "Technical Sales Representatives nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "231111",
    occupation: "Aeroplane Pilot",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "231113",
    occupation: "Flying Instructor",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "231114",
    occupation: "Helicopter Pilot",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "231213",
    occupation: "Ship's Master",
    list: "ROL",
    skillLevel: "2",
  },
  {
    anzsco: "232111",
    occupation: "Architect",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "232112",
    occupation: "Landscape Architect",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "232212", occupation: "Surveyor", list: "MLTSSL", skillLevel: "1" },
  {
    anzsco: "232213",
    occupation: "Cartographer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "232214",
    occupation: "Other Spatial Scientist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "232311",
    occupation: "Fashion Designer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "232312",
    occupation: "Industrial Designer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "232313",
    occupation: "Jewellery Designer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "232411",
    occupation: "Graphic Designer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "232412",
    occupation: "Illustrator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "232413",
    occupation: "Multimedia Designer",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "232414",
    occupation: "Web Designer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "232511",
    occupation: "Interior Designer",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "232611",
    occupation: "Urban and Regional Planner",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "233111",
    occupation: "Chemical Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233112",
    occupation: "Materials Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233211",
    occupation: "Civil Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233212",
    occupation: "Geotechnical Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233213",
    occupation: "Quantity Surveyor",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233214",
    occupation: "Structural Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233215",
    occupation: "Transport Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233311",
    occupation: "Electrical Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233411",
    occupation: "Electronics Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233511",
    occupation: "Industrial Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233512",
    occupation: "Mechanical Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233513",
    occupation: "Production or Plant Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233611",
    occupation: "Mining Engineer (excluding Petroleum)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233612",
    occupation: "Petroleum Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233911",
    occupation: "Aeronautical Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233912",
    occupation: "Agricultural Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233913",
    occupation: "Biomedical Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233914",
    occupation: "Engineering Technologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233915",
    occupation: "Environmental Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233916",
    occupation: "Naval Architect / Marine Designer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "233999",
    occupation: "Engineering Professionals nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234111",
    occupation: "Agricultural Consultant",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234112",
    occupation: "Agricultural Scientist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234113",
    occupation: "Forester / Forest Scientist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "234211", occupation: "Chemist", list: "MLTSSL", skillLevel: "1" },
  {
    anzsco: "234212",
    occupation: "Food Technologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "234213", occupation: "Wine Maker", list: "ROL", skillLevel: "1" },
  {
    anzsco: "234311",
    occupation: "Conservation Officer",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "234312",
    occupation: "Environmental Consultant",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234313",
    occupation: "Environmental Research Scientist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234399",
    occupation: "Environmental Scientists nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "234411", occupation: "Geologist", list: "STSOL", skillLevel: "1" },
  {
    anzsco: "234412",
    occupation: "Geophysicist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234413",
    occupation: "Hydrogeologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234511",
    occupation: "Life Scientist (General)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234513",
    occupation: "Biochemist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234514",
    occupation: "Biotechnologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "234515", occupation: "Botanist", list: "MLTSSL", skillLevel: "1" },
  {
    anzsco: "234516",
    occupation: "Marine Biologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "234517",
    occupation: "Microbiologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "241111",
    occupation: "Early Childhood (Pre-primary School) Teacher",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "241213",
    occupation: "Primary School Teacher",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "241311",
    occupation: "Middle School Teacher / Intermediate School Teacher",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "241411",
    occupation: "Secondary School Teacher",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "241511",
    occupation: "Special Needs Teacher",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "241512",
    occupation: "Teacher of the Hearing Impaired",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "241513",
    occupation: "Teacher of the Sight Impaired",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "241599",
    occupation: "Special Education Teachers nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "242111",
    occupation: "University Lecturer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "242211",
    occupation: "Vocational Education Teacher / Polytechnic Teacher",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "249111",
    occupation: "Education Adviser",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "249211",
    occupation: "Art Teacher (Private Tuition)",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "249212",
    occupation: "Dance Teacher (Private Tuition)",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "249214",
    occupation: "Music Teacher (Private Tuition)",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "249299",
    occupation: "Private Tutors and Teachers nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "249311",
    occupation: "Teacher of English to Speakers of Other Languages",
    list: "STSOL",
    skillLevel: "1",
  },
  { anzsco: "251111", occupation: "Dietitian", list: "STSOL", skillLevel: "1" },
  {
    anzsco: "251112",
    occupation: "Nutritionist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251211",
    occupation: "Medical Diagnostic Radiographer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "251212",
    occupation: "Medical Radiation Therapist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "251213",
    occupation: "Nuclear Medicine Technologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "251214",
    occupation: "Sonographer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "251311",
    occupation: "Environmental Health Officer",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "251312",
    occupation: "Occupational Health and Safety Adviser",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251411",
    occupation: "Optometrist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "251412",
    occupation: "Orthoptist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251511",
    occupation: "Hospital Pharmacist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251512",
    occupation: "Industrial Pharmacist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251513",
    occupation: "Retail Pharmacist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251911",
    occupation: "Health Promotion Officer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "251912",
    occupation: "Orthotist or Prosthetist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "251999",
    occupation: "Health Diagnostic and Promotion Professionals nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "252111",
    occupation: "Chiropractor",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "252112",
    occupation: "Osteopath",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "252211",
    occupation: "Acupuncturist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "252213",
    occupation: "Naturopath",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "252214",
    occupation: "Traditional Chinese Medicine Practitioner",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "252299",
    occupation: "Complementary Health Therapists nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "252311",
    occupation: "Dental Specialist",
    list: "STSOL",
    skillLevel: "1",
  },
  { anzsco: "252312", occupation: "Dentist", list: "ROL", skillLevel: "1" },
  {
    anzsco: "252411",
    occupation: "Occupational Therapist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "252511",
    occupation: "Physiotherapist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "252611",
    occupation: "Podiatrist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "252711",
    occupation: "Audiologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "252712",
    occupation: "Speech Pathologist / Speech Language Therapist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253111",
    occupation: "General Practitioner",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253112",
    occupation: "Resident Medical Officer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "253211",
    occupation: "Anaesthetist",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "253311",
    occupation: "Specialist Physician (General Medicine)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253312",
    occupation: "Cardiologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253313",
    occupation: "Clinical Haematologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253314",
    occupation: "Medical Oncologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253315",
    occupation: "Endocrinologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253316",
    occupation: "Gastroenterologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253317",
    occupation: "Intensive Care Specialist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253318",
    occupation: "Neurologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253321",
    occupation: "Paediatrician",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253322",
    occupation: "Renal Medicine Specialist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253323",
    occupation: "Rheumatologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253324",
    occupation: "Thoracic Medicine Specialist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253399",
    occupation: "Specialist Physicians nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253411",
    occupation: "Psychiatrist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253511",
    occupation: "Surgeon (General)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253512",
    occupation: "Cardiothoracic Surgeon",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253513",
    occupation: "Neurosurgeon",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253514",
    occupation: "Orthopaedic Surgeon",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253515",
    occupation: "Otorhinolaryngologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253516",
    occupation: "Paediatric Surgeon",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253517",
    occupation: "Plastic and Reconstructive Surgeon",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253518",
    occupation: "Urologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253521",
    occupation: "Vascular Surgeon",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253911",
    occupation: "Dermatologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253912",
    occupation: "Emergency Medicine Specialist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253913",
    occupation: "Obstetrician and Gynaecologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253914",
    occupation: "Ophthalmologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253915",
    occupation: "Pathologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253917",
    occupation: "Diagnostic and Interventional Radiologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253918",
    occupation: "Radiation Oncologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "253999",
    occupation: "Medical Practitioners nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  { anzsco: "254111", occupation: "Midwife", list: "MLTSSL", skillLevel: "1" },
  {
    anzsco: "254211",
    occupation: "Nurse Educator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "254212",
    occupation: "Nurse Researcher",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "254311",
    occupation: "Nurse Manager",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "254411",
    occupation: "Nurse Practitioner",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254412",
    occupation: "Registered Nurse (Aged Care)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254413",
    occupation: "Registered Nurse (Child and Family Health)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254414",
    occupation: "Registered Nurse (Community Health)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254415",
    occupation: "Registered Nurse (Critical Care and Emergency)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254416",
    occupation: "Registered Nurse (Developmental Disability)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254417",
    occupation: "Registered Nurse (Disability and Rehabilitation)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254418",
    occupation: "Registered Nurse (Medical)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254421",
    occupation: "Registered Nurse (Medical Practice)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254422",
    occupation: "Registered Nurse (Mental Health)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254423",
    occupation: "Registered Nurse (Perioperative)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254424",
    occupation: "Registered Nurse (Surgical)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254425",
    occupation: "Registered Nurse (Paediatrics)",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "254499",
    occupation: "Registered Nurses nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261111",
    occupation: "ICT Business Analyst",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261112",
    occupation: "Systems Analyst",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261211",
    occupation: "Multimedia Specialist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261212",
    occupation: "Web Developer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "261311",
    occupation: "Analyst Programmer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261312",
    occupation: "Developer Programmer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261313",
    occupation: "Software Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "261314",
    occupation: "Software Tester",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "261399",
    occupation: "Software and Applications Programmers nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "262111",
    occupation: "Database Administrator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "262112",
    occupation: "ICT Security Specialist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "262113",
    occupation: "Systems Administrator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263111",
    occupation: "Computer Network and Systems Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "263112",
    occupation: "Network Administrator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263113",
    occupation: "Network Analyst",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263211",
    occupation: "ICT Quality Assurance Engineer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263212",
    occupation: "ICT Support Engineer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263213",
    occupation: "ICT Systems Test Engineer",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263299",
    occupation: "ICT Support and Test Engineers nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "263311",
    occupation: "Telecommunications Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "263312",
    occupation: "Telecommunications Network Engineer",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "271111",
    occupation: "Barrister",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "271214",
    occupation: "Intellectual Property Lawyer",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "271299",
    occupation: "Judicial and Other Legal Professionals nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "271311",
    occupation: "Solicitor",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "272111",
    occupation: "Careers Counsellor",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272112",
    occupation: "Drug and Alcohol Counsellor",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272113",
    occupation: "Family and Marriage Counsellor",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272114",
    occupation: "Rehabilitation Counsellor",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272115",
    occupation: "Student Counsellor",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272199",
    occupation: "Counsellors nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272311",
    occupation: "Clinical Psychologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "272312",
    occupation: "Educational Psychologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "272313",
    occupation: "Organisational Psychologist",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "272314",
    occupation: "Psychotherapist",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272399",
    occupation: "Psychologists nec",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "272412",
    occupation: "Interpreter",
    list: "STSOL",
    skillLevel: "1",
  },
  { anzsco: "272413", occupation: "Translator", list: "ROL", skillLevel: "1" },
  {
    anzsco: "272499",
    occupation: "Social Professionals nec",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272511",
    occupation: "Social Worker",
    list: "MLTSSL",
    skillLevel: "1",
  },
  {
    anzsco: "272611",
    occupation: "Community Arts Worker",
    list: "ROL",
    skillLevel: "1",
  },
  {
    anzsco: "272612",
    occupation: "Recreation Officer / Recreation Coordinator",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "272613",
    occupation: "Welfare Worker",
    list: "STSOL",
    skillLevel: "1",
  },
  {
    anzsco: "311111",
    occupation: "Agricultural Technician",
    list: "ROL",
    skillLevel: "2",
  },
  {
    anzsco: "311211",
    occupation: "Anaesthetic Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "311212",
    occupation: "Cardiac Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "311213",
    occupation: "Medical Laboratory Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "311214",
    occupation: "Operating Theatre Technician",
    list: "ROL",
    skillLevel: "3",
  },
  {
    anzsco: "311215",
    occupation: "Pharmacy Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "311216",
    occupation: "Pathology Collector / Phlebotomist",
    list: "ROL",
    skillLevel: "3",
  },
  {
    anzsco: "311299",
    occupation: "Medical Technicians nec",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "311312",
    occupation: "Meat Inspector",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "311399",
    occupation: "Primary Products Inspectors nec",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "312212",
    occupation: "Civil Engineering Technician",
    list: "MLTSSL",
    skillLevel: "2",
  },
  {
    anzsco: "312311",
    occupation: "Electrical Engineering Draftsperson",
    list: "MLTSSL",
    skillLevel: "2",
  },
  {
    anzsco: "312312",
    occupation: "Electrical Engineering Technician",
    list: "MLTSSL",
    skillLevel: "2",
  },
  {
    anzsco: "312511",
    occupation: "Mechanical Engineering Draftsperson",
    list: "ROL",
    skillLevel: "2",
  },
  {
    anzsco: "312512",
    occupation: "Mechanical Engineering Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "312611",
    occupation: "Safety Inspector",
    list: "ROL",
    skillLevel: "2",
  },
  {
    anzsco: "312911",
    occupation: "Maintenance Planner",
    list: "ROL",
    skillLevel: "2",
  },
  {
    anzsco: "312912",
    occupation: "Metallurgical or Materials Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "312913",
    occupation: "Mine Deputy",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "312999",
    occupation: "Building and Engineering Technicians nec",
    list: "ROL",
    skillLevel: "2",
  },
  {
    anzsco: "313111",
    occupation: "Hardware Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "313112",
    occupation: "ICT Customer Support Officer",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "313113",
    occupation: "Web Administrator",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "313199",
    occupation: "ICT Support Technicians nec",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "313211",
    occupation: "Hardware Technician",
    list: "STSOL",
    skillLevel: "2",
  },
  {
    anzsco: "313212",
    occupation: "Telecommunications Field Engineer",
    list: "MLTSSL",
    skillLevel: "2",
  },
  {
    anzsco: "313213",
    occupation: "Telecommunications Network Planner",
    list: "MLTSSL",
    skillLevel: "2",
  },
  {
    anzsco: "313214",
    occupation: "Telecommunications Technical Officer or Technologist",
    list: "MLTSSL",
    skillLevel: "2",
  },
  {
    anzsco: "321111",
    occupation: "Automotive Electrician",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "321211",
    occupation: "Motor Mechanic (General)",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "321212",
    occupation: "Diesel Motor Mechanic",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "321213",
    occupation: "Motorcycle Mechanic",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "321214",
    occupation: "Small Engine Mechanic",
    list: "MLTSSL",
    skillLevel: "3",
  },
  { anzsco: "322113", occupation: "Farrier", list: "STSOL", skillLevel: "3" },
  {
    anzsco: "322211",
    occupation: "Sheetmetal Trades Worker",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "322311",
    occupation: "Metal Fabricator",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "322312",
    occupation: "Pressure Welder",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "322313",
    occupation: "Welder (First Class) (Aus) / Welder (NZ)",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "323111",
    occupation: "Aircraft Maintenance Engineer (Avionics)",
    list: "STSOL",
    skillLevel: "3",
  },
  {
    anzsco: "323112",
    occupation: "Aircraft Maintenance Engineer (Mechanical)",
    list: "STSOL",
    skillLevel: "3",
  },
  {
    anzsco: "323113",
    occupation: "Aircraft Maintenance Engineer (Structures)",
    list: "STSOL",
    skillLevel: "3",
  },
  {
    anzsco: "323211",
    occupation: "Fitter (General)",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "323212",
    occupation: "Fitter and Turner",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "323213",
    occupation: "Fitter-Welder",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "323214",
    occupation: "Metal Machinist (First Class)",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "323299",
    occupation: "Metal Fitters and Machinists nec",
    list: "STSOL",
    skillLevel: "3",
  },
  {
    anzsco: "323313",
    occupation: "Locksmith",
    list: "MLTSSL",
    skillLevel: "3",
  },
  {
    anzsco: "323314",
    occupation: "Precision Instrument Maker and Repairer",
    list: "STSOL",
    skillLevel: "3",
  },
  { anzsco: "323412", occupation: "Toolmaker", list: "STSOL", skillLevel: "3" },
  {
    anzsco: "324111",
    occupation: "Panelbeater",
    list: "MLTSSL",
    skillLevel: "3",
  },
];
export default data;
